kind: Pod
apiVersion: v1
metadata:
  name: parity
  labels:
    app: parity

spec:
  containers:
    - name: parity
      image: parity/parity:v1.7.0
      resources:
        limits:
          memory: 2Gi
        requests:
          memory: 1Gi

      ports:
      - containerPort: 8545
      args: ["--geth", "--unsafe-expose"]
      volumeMounts:
      - mountPath: "/root/.local/share/io.parity.ethereum/"
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: parity-disk
